### ISSUE TITLE
currentPlaybackTime not updated in command center

### ISSUE THREAD

**Issue by Hackmodford** [gangverk/GVMusicPlayerController#20]
I just noticed that if I change the player's currentPlaybackTime, the changes are not reflected in the command center. Any ideas how to fix this?

**Comment by kevinrenskers** [comment]
Sorry but we can't help you with issues since we don't use GVMusicPlayerController in any of our own apps. Please refer to the updated [readme](https://github.com/gangverk/GVMusicPlayerController#issues-and-questions).
