### ISSUE TITLE
Can MPMediaItemPropertyBookmarkTime be updated?

### ISSUE THREAD

**Issue by Hackmodford** [gangverk/GVMusicPlayerController#21]
Is it possible for GVMusicPlayerController to update the bookmark time?

**Comment by kevinrenskers** [comment]
Sorry but we can't help you with issues since we don't use GVMusicPlayerController in any of our own apps. Please refer to the uploaded [readme](https://github.com/gangverk/GVMusicPlayerController#issues-and-questions).
